### ISSUE TITLE
[Board] Bucket 이동 시, 기존 값 (제목)이 잠시 보이는 증상

### ISSUE THREAD

**Issue by with-key** [team-pig/pig-frontend#109]

**Comment by jiho3894** [comment]
안녕하세요 현재 항해6기 D반 수강중인 김지호라고 합니다 다름이 아니고 저희도 현재 React-beautiful-dnd를 이용한 칸반보드를 만들었는데 현재 모든 기능은 정상적으로 작동하지만 카드를 이동시킨후 바로 카드로 이동하지않고 원래 위치에 잠깐 갔다가 이동하는 깜빡이는 현상이 발생하고 있습니다 렌더링 동작 순서를 확인해본 결과 해당 버킷값에서 보드의 전체 배열을 검사하는 로직이 있는데 최초 1회에 카드 이동전 배열이 찍히는것을 확인했습니다 하지만 이후에 이 상태값을 막거나 안보이게 하는 방법을 찾지 못해 동일한 이슈를 경험한 선배님들 통해 조언을 얻고싶어서 코멘트 남깁니다 
https://github.com/sparta-team6/CO-UP-TEAM-FE/blob/master/src/layout/BoardList.tsx

**Comment by jihyunan-dev** [comment]
@jiho3894 안녕하세요 지호님:)
해당 이슈에 대한 해결은 https://github.com/team-pig/pig-frontend/commit/602e0d4983bdf3a53a495bad9d91285ae8c4e87f 커밋이었던 것으로 기억합니다.
저희는 redux를 사용했었는데요, 서버로 위치 변경 요청을 보낸 후 응답이 온 후에야 변경된 카드의 위치를 dispatch하고 있었기 때문에 발생했던 일이었습니다.
지호님의 프로젝트를 잠시 살펴보니 react-query를 사용중이시고, 변경된 위치를 따로 클라이언트에 저장하지 않고 invalidateQuery를 하여 새로 받아 보여주는 것으로 예상됩니다.
이 칸반같은 경우는 분명하게 내가 마우스를 놓는 순간 변경되는 것을 보여주는 것이 너무 당연하기 때문에 optimistic update를 함께 활용하셔서 보여주시면 훨씬 좋아지지 않을까 의견드립니다:)

**Comment by jiho3894** [comment]
방향성을 제시해주신 덕분에 어느정도 접근했습니다 팀원들과 고민하고 해결해보도록 하겠습니다 정말 감사합니다!
