### ISSUE TITLE
안녕하세요 예상기 매니저님 !! 안지현 매니저님 

### ISSUE THREAD

**Issue by ho-bolt** [team-pig/pig-frontend#277]
안녕하세요 예상기님, 안지현님!  저는 항해 6기로 노드를 공부하고 있는 서호진이라고 합니다! 
다름이 아니라 협업돼지를 하신 걸 보고 궁금해서 여쭤보고 싶은 게 있습니다!
협업돼지에서 웹 에디터를 사용하시는데 웹에디터에서 이미지와 글을 동시에 작성했을 때 이걸 어떻게 처리하셨나요?? 노드 코드를 보면 그냥 content만 바디로 받고 이미지 처리하는 코드가 보이질 않아서 혹시 프론트에서 처리를 어떻게 하셨는 지 궁금해서 여쭤봅니다! 
저희는 프론트에서 해주시는 분은 이미지를 받으면 base64로 백으로 전달해드리고 제가 그걸 url로 바꾼다음에 db에 저장하는 것 같다고 말씀을 해주셨는데 그걸 studyNote라는 하나의 바디로 받고 있어서 text를 적었을 때 이미지와 구분을 어떻게 나누는 지 잘 감이 안잡힙니다. 혹시 어떻게 이미지를 처리하셨나요..? 
긴 글 읽어주셔서 감사합니다!! 
 @with-key @jihyunan-dev

**Comment by jihyunan-dev** [comment]
@ho-bolt 호진님 안녕하세요:)
먼저 저희 프로젝트에서는 이미지 저장 로직이 프론트쪽에 있다는 답변을 드릴게요ㅎㅎ
프로젝트를 시작하면서 에디터에서의 이미지처리를 고려하지 않고 작업을 시작했고, 그 과정에서 에디터에 이미지를 삽입하면 엄청난 문자열(base64)이 에디터에 입력되는 것을 확인했습니다.
당시 백엔드 분들께서 다른 기능에 매진 중이셨기 때문에 저희는 프론트에서 s3로 바로 보내는 작업을 진행했습니다.
계속 프론트에 둘 생각은 아니었습니다. 하지만 다른 추가 기능이나 예외처리, 그리고 피드백 반영 등이 더 우선순위에 있었기 때문에 동작하는 것을 굳이 바꾸지 않았던 것이 저희의 히스토리 입니다.

결과적으로 저희는 에디터에서 이미지가 삽입됐을 시 프론트에서 s3로 보내 image url을 받아 렌더한 뒤, 에디터의 글 + 이미지url이 된 묶음을 서버에 저장했습니다.

하지만 이 방법이 베스트였다고 생각하지는 않습니다.
s3에 쓰지 않는 이미지들을 처리하지 못한 것이 하나의 예시인데요, 이 부분은 아마 이미 고민하고 계시거나 앞으로 만들어가시면서 고민하실 것 같습니다🙂

더 궁금한 점이 있으면 말씀해주세요 ㅎㅎ

**Comment by ho-bolt** [comment]
아하  그렇군요 오래전에 작업하셨는데도 답변 달아주셔서 감사합니다!!!

**Comment by with-key** [comment]
discord에 webhook이 걸려있어서 봤네요 ㅎㅎ @ho-bolt

**Comment by jihyunan-dev** [comment]
이슈 클로즈합니닷
